"""
export_coords.py
Write the survey's contact coords to a clean, importable Python file so a
coworker's script can pull them in with one line:

    from contacts_coords import coords      # [(lat, lon, 0), ...]

The output is a normal Python module — a single `coords` list of
(lat, lon, third) tuples plus a header comment recording how it was made.
This is the single writer used by the end-of-survey hand-off (main.py) and the
replay tool; planner_handoff.py falls back to it when no planner is wired.
"""

import time


def render_coords_module(coords, var="coords", largest=None, min_hits=None):
    """Return the text of an importable Python module defining `var = [...]`."""
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    filt = []
    if largest is not None:
        filt.append(f"largest {largest} by area")
    if min_hits is not None:
        filt.append(f"hits >= {min_hits}")
    filt_note = (" (" + ", ".join(filt) + ")") if filt else ""

    lines = [
        "# Auto-generated by the BlueBoat survey — do not edit by hand.",
        f"# {len(coords)} contact(s){filt_note}, generated {stamp}.",
        "#",
        f"# Each tuple is (lat, lon, {var}[i][2]); the 3rd slot is 0 unless set.",
        f"# Use it elsewhere with:  from contacts_coords import {var}",
        "",
        f"{var} = [",
    ]
    lines += [f"    ({lat}, {lon}, {third})," for lat, lon, third in coords]
    lines.append("]")
    return "\n".join(lines) + "\n"


def write_coords_file(coords, path="contacts_coords.py", var="coords",
                      largest=None, min_hits=None):
    """Write `coords` to `path` as an importable module. Returns (path, count)."""
    with open(path, "w") as f:
        f.write(render_coords_module(coords, var=var,
                                     largest=largest, min_hits=min_hits))
    return path, len(coords)


def export_from_log(log, path="contacts_coords.py", var="coords",
                    largest=50, min_hits=2):
    """Convenience: pull the largest contacts straight from a DetectionLog and
    write the importable file. Defaults match the end-of-survey hand-off."""
    coords = log.to_coords(largest=largest, min_hits=min_hits)
    return write_coords_file(coords, path=path, var=var,
                             largest=largest, min_hits=min_hits)
